apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g3mxp6zqp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g3mxp6zqp-nodejs 
  name: g3mxp6zqp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g3mxp6zqp-nodejs 
